First draft of a custom Audio Player
Lift-app/lift-web pull request #30
Opened 2017-05-22 09:42 UTC by muse

Wrong branch name, correct intentions

2017-05-22 09:50 UTC, soudy requested changes

2017-05-22 09:50 UTC, soudy commented on src/components/card/Card.vue
> +      <h2 class="title"
Can we keep this on one line?

2017-05-22 09:50 UTC, soudy commented on src/components/card/Card.vue
> +        {{ post_data.body }}
Can we use `post` instead of `post_data`?

2017-05-22 09:50 UTC, soudy commented on src/components/player/Player.vue.js
> +          , 'BPlay': '.button-play'
Can you format this like it's JavaScript and not Haskell?

2017-05-22 09:50 UTC, soudy commented on src/components/player/Player.vue.js
> +    this.$ = {
What does `$` mean here?

2017-05-22 09:50 UTC, soudy commented on src/components/player/Player.vue.js
> +          return `${Math.floor(number / 60)}:${mod < 10 ? `0${mod}` : mod}`
Could use some variables here

2017-05-22 09:50 UTC, soudy commented on src/components/player/Player.vue.js
> +      fn: {
`fn` is a bit non-descriptive

2017-05-22 09:50 UTC, soudy commented on src/components/player/Player.vue.js
> +      Object.assign( this.$.el
Extra space after function call

2017-05-22 09:50 UTC, soudy commented on src/components/player/Player.vue.js
> +                   , controls( {}
Formatting :-1:

2017-05-22 09:50 UTC, soudy commented on src/components/player/Player.vue.js
> +      this.$.el.TAudio.paused
Put this in a `toggle` function?

2017-05-22 09:50 UTC, soudy commented on src/components/player/Player.vue.js
> +      this.$.el.PBar.max        = MTime
Formatting

2017-05-22 10:00 UTC, Steun commented on src/pages/create-post/CreatePost.vue.js
> +//import Player from "@/components/Player/Player"
WTF REMOVE COMMENT RIGHT NAO CODE CLEAN PLS 👎 👎 👎

2017-05-22 12:19 UTC, soudy commented on src/components/player/Player.vue.js
> +          return `${Math.floor(number / 60)}:${mod < 10 ? `0${mod}` : mod}`
Also, `mod` is non-descriptive

2017-05-22 12:20 UTC, soudy commented on src/components/card/Card.vue
> +        @click="haltAction"
`haltAction` was removed, wasn't it?

2017-05-30 11:48 UTC, soudy commented on src/components/player/Player.vue.js
> +        remainder: (delete object[key], object)
Isn't it useless to return the remainder, as `delete` mutates the object passed to it?

2017-05-30 11:53 UTC, soudy commented on src/components/player/Player.vue.js
> +        ? this._controls.apply(null, [accumulator, container, item.remainder])
Why apply here and not just `this._controls(accumulator, container, item.remainder)`?

2017-05-30 11:55 UTC, soudy commented on src/components/player/Player.vue.js
> +      return `${Math.floor(number / 60)}:${mod < 10 ? `0${mod}` : mod}`
Variables :sob:

2017-05-30 11:57 UTC, soudy commented on src/components/player/Player.vue.js
> +    _switch(controls) {
`toggle` a better name?

2017-09-08 11:44 UTC, closed without merging